version: "3.8"

networks:
  discord-logger:
    driver: bridge

services:
  postgres:
    networks:
      - discord-logger
    image: postgres:latest
    container_name: discord-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - db:/var/lib/postgresql/data

  app:
    networks:
      - discord-logger
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-app
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - postgres

volumes:
  db:
