version: "3.8"

networks:
  discord-logger:
    driver: bridge

services:
  app:
    networks:
      - discord-logger
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-app
    ports:
      - 8080:8080
    volumes:
      - .:/app

volumes:
  db:
